#+STARTUP: showall indent

* Fakeymacs extension

** ■ SpaceFN を実現する設定を行う

SpaceFN を実現する設定を行う拡張機能です。

*** コンフィグレーションパラメータ

|----------------------------------+----------------------------------------------------------------------------------------------------|
| Configuration parameter          | Description                                                                                        |
|----------------------------------+----------------------------------------------------------------------------------------------------|
| fc.space_fn_key                  | SpaceFN 用のモディファイアキーを指定する                                                           |
| fc.space_fn_window_keymap_list   | SpaceFN を適用するキーマップを指定する                                                             |
| fc.space_fn_use_oneshot_function | SpaceFN 用のモディファイアキーの単押しで、元のキーの機能を利用するかどうかを指定する               |
| fc.space_fn_delay_seconds        | SpaceFN 用のモディファイアキーが押下されてから、SpacdFN の機能が働くようになるまでの秒数を指定する |
|----------------------------------+----------------------------------------------------------------------------------------------------|

*** 留意事項

● 初期の設定では、SpaceFN を実現するベースの設定のみを行っています。SpaceFN のキー設定を
行う際は、_config_personal_1.py もしくは _config_personal_2.py を config_personal.py
に複写し、そのファイルの中で行うようにしてください。

● _config_personal_1.py は、Ctrl キーや Alt キーとの組み合わせも含め、できるだけ完全な
キーの複製を行う設定サンプルです。
_config_personal_2.py は、Ctrl キーや Alt キーとの組み合わせは行わない、キー単体と Shift
キーの組み合わせのみのキーの複製を行う設定サンプルです。
SpaceFN は、設定を行っていない SpaceFN のキーを入力すると、SpaceFN 用のモディファイア
キーを除いたキーを発行する機能を持っています。そして 本拡張機能の SpaceFN の場合は、
Emacs キーバインドの機能ではなく、Windows 本来のキーの機能が実行される仕様となっています。
この機能を活用することにより、SpaceFN 用のモディファイアキーを押してから Ctrl+x や Ctrl+c
などのキーを入力すると、Windows 本来のキーの機能の「カット」や「コピー」などを利用する
ことができます。
HHKB US キーボードのように、Ctrl キーが一つしか持てない（CapsLock キーに RCtrl キーを
割当てられない）キーボードを使って Fakeymacs の Emacs キーバインドを利用する場合、
Windows 本来のキーの機能を利用するために Ctrl+q を前置する方法がありますが、本説明の
機能を用いることで、同等の機能を実現することができます。
_config_personal_2.py は、この機能を利用する場合の設定サンプルとしてご利用ください。

● SpaceFN 用のモディファイアキーと組み合わせ可能なモディファイアキーは、Ctrl キー、
Alt キー、Shift キーとします（Win キーは除きます）。
これは、Keyhac に登録可能なキーの上限を超えてエラーが発生するようになったことによる
制限事項となります。

● 本拡張機能の SpaceFN は、初期値として keymap_emacs、keymap_im 及び keymap_vscode
（vscode Extension を利用している場合）のキーマップのみで動作するようにしています。
fc.space_fn_window_keymap_list 変数の指定ににより、SpaceFN を適用するキーマップを
変更することができます。

● 本拡張機能の SpaceFN は、SpaceFN 用のモディファイアキーが押下されてから
fc.space_fn_delay_seconds 変数に指定した秒数（初期値：0.15秒）後に次のキーが押された場合に、
SpaceFN の機能が働くようにしています。
fc.space_fn_delay_seconds 変数に指定した秒数より前に次のキーを押下した場合は、その押下した
キーがそのまま入力される仕様としており、key rollover の対策としています。

● 本拡張機能の SpaceFN を利用する場合は、必ず SpaceFN 用のモディファイアキー（初期値は
Space）から入力するようにしてください。本拡張機能の SpaceFN は、Shift や Ctrl などその他の
モディファイアキーと組み合わせて利用することもできますが、その他のモディファイアキーを
最初に入力した場合には、SpaceFN 用のモディファイアキーを入力した時点でキーの入力が
確定する仕様としています。（これは、Ctrl+Space や Shift+Space を遅延なく入力できるように
する対策です。）

● SpaceFN については、以下のサイトを参考としています。

- https://geekhack.org/index.php?topic=51069.0
- http://martin-stone.github.io/touchcursor/
