#+STARTUP: showall indent

* Fakeymacs extension

** ■ SpaceFn を実現する設定を行う

SpaceFn を実現する設定を行う拡張機能です。

Emacs キーバインドの機能があれば使う必要がないものと思われますが、サンプル的な実装として
作成してみました。

*** コンフィグレーションパラメータ

|--------------------------------+------------------------------------------|
| Configuration parameter        | Description                              |
|--------------------------------+------------------------------------------|
| fc.space_fn_key                | SpaceFn 用のモディファイアキーを指定する |
| fc.space_fn_window_keymap_list | SpaceFn を適用するキーマップを指定する   |
|--------------------------------+------------------------------------------|

*** 留意事項

● 初期の設定では、SpaceFn を実現するベースの設定のみを行っています。SpaceFn のキー設定を
行う際は、_config_personal_1.py もしくは _config_personal_2.py を config_personal.py
に複写し、そのファイルの中で行うようにしてください。

● _config_personal_1.py は、Ctrl キーや Alt キーとの組み合わせも含め、できるだけ完全な
キーの複製を行う設定サンプルです。_config_personal_2.py は、Ctrl キーや Alt キーとの
組み合わせは行わない、キー単体と Shift キーの組み合わせのみのキーの複製を行う設定サンプル
です。本拡張機能の SpaceFn は、設定を行っていない SpaceFn のキーを入力すると、SpaceFn
用のモディファイアキーを除いたキーを発行する副作用を持っています。この副作用を活用する
ことにより、SpaceFn 用のモディファイアキーを押してから Ctrl+x や Ctrl+c などのキーを
入力すると、Windows 本来のキーの機能の「カット」や「コピー」などを利用することができます。
HHKB US キーボードのように、Ctrl キーが一つしか持てない（CapsLock キーの RCtrl キーを
割当てられない）キーボードを使って Fakeymacs の Emacs キーバインドを利用する場合、
Windows 本来の機能のキーを入力するためには Ctrl+q を前置する方法がありますが、本説明の
副作用を用いることで、これと同様の機能の実現することができます。
_config_personal_2.py は、この副作用を利用する場合の設定サンプルとしてご利用ください。

● 本拡張機能の SpaceFn は、Emacs 日本語入力モードの利用時には機能が働かないように設定
しています。これは、SpaceFn 用のモディファイアキーに Space を利用した場合、日本語入力時
に変換漏れが発生することを回避するためです。このため、本拡張機能を利用する際は、Emacs
日本語入力モードを利用する設定（初期値は有効）とするか、SpaceFn 用のモディファイアキー
を Space 以外のキー（「無変換」キーなど）にすることをお勧めします。

● 本拡張機能の SpaceFn は、初期値として keymap_emacs と keymap_im のキーマップのみで
動作するようにしています。これは、上記に記載している日本語入力の問題を回避するため、
Emacs 日本語入力モードが使えるキーマップのみを SpaceFn の対象としているためです。
SpaceFn の対象とするキーマップの指定は fc.space_fn_window_keymap_list 変数で行なえますので、
SpaceFn 用のモディファイアキーを Space 以外のキー（「無変換」キーなど）にして利用する
場合は、fc.space_fn_window_keymap_list 変数 に keymap_base を追加することで、
より広い範囲で SpaceFn の機能を利用することができるようになります。

● 本拡張機能の SpaceFn を利用する場合は、必ず最初に fc.space_fn_key 変数で指定したキー
（初期値は Space）から入力するようにしてください。本拡張機能の SpaceFn は、Shift や Ctrl
などのその他のモディファイアキーと組み合わせて利用することもできますが、その他のモディファイア
キーを最初に入力した場合には、fc.space_fn_key 変数に指定したキーを入力した時点で、
キーの入力が確定する仕様としています。（これは、Ctrl+Space や Shift+Space を遅延なく入力
できるようする対策です。）

● SpaceFn については、以下のサイトを参考としています。

- https://geekhack.org/index.php?topic=51069.0
- http://martin-stone.github.io/touchcursor/
