#+STARTUP: showall indent

* Fakeymacs extension

** ■ SpaceFn を実現する設定を行う

SpaceFn を実現する設定を行う拡張機能です。

Emacs キーバインドの機能があれば使う必要がないものと思われますが、サンプル的な実装として
作成してみました。

*** コンフィグレーションパラメータ

|-------------------------+------------------------------------------|
| Configuration parameter | Description                              |
|-------------------------+------------------------------------------|
| fc.space_fn_key         | SpaceFn 用のモディファイアキーを指定する |
|-------------------------+------------------------------------------|

*** 留意事項

● 初期の設定では、SpaceFn を実現するベースの設定のみを行っています。SpaceFn のキー設定を
行う際は、_config_personal.py を複写して config_personal.py を作成し、そのファイルの中で
行うようにしてください。

● 本拡張機能の SpaceFn は、keymap_emacs のキーマップが適用されるアプリケーションソフトで、
かつ、User0 と Shift のモディファイアキーと組み合わせたキー設定のみで正常動作します。
この制約は、SpaceFn 用のモディファイアキーに Space を利用した場合、Emacs キーバインドで
用いる C-Space などで誤動作が発生することを回避するためです。

● 本拡張機能の SpaceFn は、Emacs 日本語入力モードの利用時には機能が働かないように設定
しています。これは、SpaceFn 用のモディファイアキーに Space を利用した場合、日本語入力時
に変換漏れが発生することを回避するためです。このため、本拡張機能を利用する際は、Emacs
日本語入力モードを利用する設定（初期値は有効）とするか、SpaceFn 用のモディファイアキー
を Space 以外のキー（「変換」キーなど）にすることをお勧めします。

● SpaceFn については、以下のサイトを参考としています。

- https://geekhack.org/index.php?topic=51069.0
- http://martin-stone.github.io/touchcursor/
