#+STARTUP: showall indent

* Fakeymacs extension

** ■ SpaceFN を実現する設定を行う

SpaceFN を実現する設定を行う拡張機能です。

*** コンフィグレーションパラメータ

|-----------------------------------+--------------------------------------------------------------------------------------|
| Configuration parameter           | Description                                                                          |
|-----------------------------------+--------------------------------------------------------------------------------------|
| fc.space_fn_key                   | SpaceFN 用のモディファイアキーを指定する                                             |
| fc.space_fn_window_keymap_list    | SpaceFN を適用するキーマップを指定する                                               |
| fc.space_fn_use_one_shot_function | SpaceFN 用のモディファイアキーの単押しで、元のキーの機能を利用するかどうかを指定する |
|-----------------------------------+--------------------------------------------------------------------------------------|

*** 留意事項

● 初期の設定では、SpaceFN を実現するベースの設定のみを行っています。SpaceFN のキー設定を
行う際は、_config_personal_1.py もしくは _config_personal_2.py を config_personal.py
に複写し、そのファイルの中で行うようにしてください。

● _config_personal_1.py は、Ctrl キーや Alt キーとの組み合わせも含め、できるだけ完全な
キーの複製を行う設定サンプルです。
_config_personal_2.py は、Ctrl キーや Alt キーとの組み合わせは行わない、キー単体と Shift
キーの組み合わせのみのキーの複製を行う設定サンプルです。
SpaceFN は、設定を行っていない SpaceFN のキーを入力すると、SpaceFN 用のモディファイア
キーを除いたキーを発行する機能を持っています。そして 本拡張機能の SpaceFN の場合は、
Emacs キーバインドの機能ではなく、Windows 本来のキーの機能が実行される仕様となっています。
この機能を活用することにより、SpaceFN 用のモディファイアキーを押してから Ctrl+x や Ctrl+c
などのキーを入力すると、Windows 本来のキーの機能の「カット」や「コピー」などを利用する
ことができます。
HHKB US キーボードのように、Ctrl キーが一つしか持てない（CapsLock キーに RCtrl キーを
割当てられない）キーボードを使って Fakeymacs の Emacs キーバインドを利用する場合、
Windows 本来のキーの機能を利用するために Ctrl+q を前置する方法がありますが、本説明の
機能を用いることで、同等の機能を実現することができます。
_config_personal_2.py は、この機能を利用する場合の設定サンプルとしてご利用ください。

● SpaceFN 用のモディファイアキーと組み合わせ可能なモディファイアキーは、Ctrl キー、
Alt キー、Shift キーとします（Win キーは除きます）。
これは、Keyhac に登録可能はキーの上限を超えてエラーが発生するようになったことによる対策
（制限事項）によるものです。

● 本拡張機能の SpaceFN は、Emacs 日本語入力モードの利用時には機能が働かないように設定
しています。これは、SpaceFN 用のモディファイアキーに Space（初期値）を利用した場合、
日本語入力時に変換漏れが発生することを回避するためです。このため、本拡張機能を利用する際は、
Emacs 日本語入力モードを利用する設定（初期値は有効）とするか、SpaceFN 用のモディファイアキー
を Space 以外のキー（「無変換」キーなど）にすることをお勧めします。

● 本拡張機能の SpaceFN は、初期値として keymap_emacs、keymap_im 及び keymap_vscode
（vscode Extension を利用している場合）のキーマップのみで動作するようにしています。
これは、上記に記載している日本語入力の問題を回避するため、Emacs 日本語入力モードが使える
キーマップのみを SpaceFN の対象としているためです。
SpaceFN の対象とするキーマップの指定は fc.space_fn_window_keymap_list 変数で行なえますので、
SpaceFN 用のモディファイアキーを Space 以外のキー（「無変換」キーなど）にして利用する
場合は、fc.space_fn_window_keymap_list 変数 に keymap_base を追加することで、
より広い範囲で SpaceFN の機能を利用することができるようになります。

● 本拡張機能の SpaceFN を利用する場合は、必ず SpaceFN 用のモディファイアキー（初期値は
Space）から入力するようにしてください。本拡張機能の SpaceFN は、Shift や Ctrl などその他の
モディファイアキーと組み合わせて利用することもできますが、その他のモディファイアキーを
最初に入力した場合には、SpaceFN 用のモディファイアキーを入力した時点で、キーの入力が
確定する仕様としています。（これは、Ctrl+Space や Shift+Space を遅延なく入力できるように
する対策です。）

● SpaceFN については、以下のサイトを参考としています。

- https://geekhack.org/index.php?topic=51069.0
- http://martin-stone.github.io/touchcursor/
