#+STARTUP: showall indent

* Fakeymacs extension

** ■ SpaceFn を実現する設定を行う

SpaceFn を実現する設定を行う拡張機能です。

Emacs キーバインドの機能があれば使う必要がないものと思われますが、サンプル的な実装として
作成してみました。

*** コンフィグレーションパラメータ

|--------------------------------+------------------------------------------|
| Configuration parameter        | Description                              |
|--------------------------------+------------------------------------------|
| fc.space_fn_key                | SpaceFn 用のモディファイアキーを指定する |
| fc.space_fn_window_keymap_list | SpaceFn を適用するキーマップを指定する   |
|--------------------------------+------------------------------------------|

*** 留意事項

● 初期の設定では、SpaceFn を実現するベースの設定のみを行っています。SpaceFn のキー設定を
行う際は、_config_personal.py を複写して config_personal.py を作成し、そのファイルの中で
行うようにしてください。

● 本拡張機能の SpaceFn は、初期値として keymap_emacs と keymap_im のキーマップのみで
動作するようにしています。これは、次に記載している日本語入力の問題を回避するため、
Emacs 日本語入力モードが使えるキーマップのみを SpaceFn の対象としているためです。
SpaceFn の対象とするキーマップの指定は fc.space_fn_window_keymap_list 変数で行なえますので、
SpaceFn 用のモディファイアキーを Space 以外のキー（「無変換」キーなど）にして利用する
場合は、fc.space_fn_window_keymap_list 変数 に keymap_base を追加することで、
より広い範囲で SpaceFn の機能を利用することができるようになります。

● 本拡張機能の SpaceFn は、Emacs 日本語入力モードの利用時には機能が働かないように設定
しています。これは、SpaceFn 用のモディファイアキーに Space を利用した場合、日本語入力時
に変換漏れが発生することを回避するためです。このため、本拡張機能を利用する際は、Emacs
日本語入力モードを利用する設定（初期値は有効）とするか、SpaceFn 用のモディファイアキー
を Space 以外のキー（「無変換」キーなど）にすることをお勧めします。

● 本拡張機能の SpaceFn を利用する場合は、必ず最初に fc.space_fn_key 変数で指定したキー
（初期値は Space）から入力するようにしてください。本拡張機能の SpaceFn は、Shift や Ctrl
などのその他のモディファイアキーと組み合わせて利用することもできますが、その他のモディファイア
キーを最初に入力した場合には、fc.space_fn_key 変数に指定したキーを入力した時点で、
キーの入力が確定する仕様としています。（これは、Ctrl+Space や Shift+Space を遅延なく入力
できるようする対策です。）

● SpaceFn については、以下のサイトを参考としています。

- https://geekhack.org/index.php?topic=51069.0
- http://martin-stone.github.io/touchcursor/
