#+STARTUP: showall indent

* Fakeymacs extension

** ■ CapsLock キーを Ctrl キーとして使うための設定を行う

管理権限を持たない PC を利用している場合でレジストリによるキーの置き換えができない場合に
CapsLock キーを Ctrl キーとして使うための設定を行う拡張機能です。

*** 留意事項

● 本機能を利用する場合、モディファイアキーとして User2（U2）が利用されます。

● fc.transparent_target 変数や fc.game_app_list 変数に指定したアプリにはこの機能は適用されません。

● fc.side_of_ctrl_key 変数を "R" に設定することで CapsLock キーを右コントロールキーとして
Emacs キーバインド用のキーとして利用することができます。この場合、左下にあるコントロールキーは
 Windows ショートカットキーやマウスとの連携用のキーとして使うことができます。

● C-CapsLock で CapsLock の切り替えを可能としています。

● 次の制約事項がありますので、ご理解の上ご利用ください。

 - CapsLock キーをマウスと組み合せて利用することはできません。
 - CapsLock キーと他のモディファイアキーを複合して使うキーバインドを入力した後、何れかの一部のモディファイアキーを離して次のキーバインドを入力することはできません。（例えば、CapsLock+Alt+l を押下した後、Alt と l のみを離して d を入力するということはできません。）
 - OS の設定が日本語キーボードの場合、キーボードマクロの記録の際に CapsLock キーを用いたキーバインドを使うことはできません。（キーボードマクロの記録の開始、終了のキーバインドで CapsLock キーを利用することは可能です。）
 - リモートデスクトップ接続先でこの機能を利用する場合には、接続元、接続先に同じバージョンの Fakeymacs をインストールし、両側で本拡張機能を有効にし、リモートデスクトップ接続の「オプション」の「ローカルリソース」->「キーボード」で「このコンピューター」を選択してから接続してください。またこの選択をする場合、接続先での一部のキーバインドが変更となることにご留意ください。
  - https://www.yellowhouse.jp/windows10remote-desktop-option/#toc13
  - https://atmarkit.itmedia.co.jp/ait/articles/0508/27/news022.html
 - VcXsrv などの X ウィンドウサーバソフトで、カーソル移動が遅くなる場合があります。（WSLg は問題なし）
